# Generated by Django 4.2.7 on 2023-12-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeApp', '0003_material_students_materials_provide'),
    ]

    operations = [
        migrations.CreateModel(
            name='chkboxcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=100)),
            ],
        ),
    ]
