# Generated by Django 4.2.7 on 2023-12-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeApp', '0005_students_coursename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='coursename',
        ),
        migrations.AddField(
            model_name='students',
            name='coursename',
            field=models.ManyToManyField(blank=True, to='collegeApp.chkboxcourse'),
        ),
    ]
