# Generated by Django 4.2.7 on 2023-12-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeApp', '0006_remove_students_coursename_students_coursename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='coursename',
        ),
        migrations.AddField(
            model_name='students',
            name='coursename',
            field=models.CharField(default='1999-09-13', max_length=100),
            preserve_default=False,
        ),
    ]
