# Generated by Django 4.2.7 on 2023-12-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeApp', '0008_remove_students_materials_provide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='address',
            field=models.TextField(blank=True, default='No address provided', null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='mail_id',
            field=models.EmailField(blank=True, default='default@example.com', max_length=254, null=True),
        ),
    ]
