# Generated by Django 4.2.7 on 2023-12-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeApp', '0009_alter_students_address_alter_students_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='coursename',
            new_name='materials_provide',
        ),
    ]
